#:kivy 1.10.1

<Ship>:
    size: 140, 140
    beam: ship_beam
    image: image
    Image:
        source: "rsc/ship32.png"
        allow_stretch: True
        id: image
        center: self.parent.center
        size: self.parent.size
    Beam:
        id: ship_beam
        center: self.parent.center

<Beam>:
    center: self.parent.center
    canvas:
        Color:
            rgba: 0.05, 0.6, 1, 0.8